db_schemas = {
    'person_data': {
        'person_id': 'Int64',
        'gender_concept_id': 'Int64',
        'gender_concept_description': 'str',
        'year_of_birth': 'Int64',
        'birth_datetime': 'datetime64[ns]',
        'race_concept_id': 'Int64',
        'ethnicity_concept_id': 'Int64',
        'person_source_value': 'str'
    },
    'condition_occurrence_data': {
        'condition_occurrence_id': 'Int64',
        'person_id': 'Int64',
        'condition_concept_id': 'Int64',
        'condition_concept_description': 'str',
        'condition_vocab': 'str',
        'condition_start_date': 'datetime64[ns]',
        'condition_type_concept_id': 'Int64',
        'condition_type_concept_description': 'str',
        'condition_status_concept_id': 'Int64',
        'condition_status_concept_description': 'str'
    },
    'measurement_data': {
        'measurement_id': 'Int64',
        'person_id': 'Int64',
        'measurement_concept_id': 'Int64',
        'measurement_concept_description': 'str',
        'measurement_concept_vocab': 'str',
        'measurement_date': 'datetime64[ns]',
        'value_as_concept_id': 'Int64',
        'value_as_concept_description': 'str',
        'value_as_concept_vocab': 'str',
        'unit_concept_id': 'Int64',
        'unit_concept_description': 'str',
        'unit_concept_vocab': 'str',
        'range_low': 'float64',
        'range_high': 'float64',
        'measurement_type_concept_id': 'Int64',
        'measurement_type_concept_description': 'str',
        'value_as_number': 'float64',
        'meas_event_field_concept_id': 'Int64',
        'meas_event_field_concept_description': 'str',
        'meas_event_field_concept_vocab': 'str'
    },
    'observation_data': {
        'observation_id': 'Int64',
        'person_id': 'Int64',
        'observation_concept_id': 'Int64',
        'observation_concept_description': 'str',
        'observation_concept_vocab': 'str',
        'observation_date': 'datetime64[ns]',
        'observation_type_concept_id': 'Int64',
        'observation_type_concept_description': 'str',
        'value_as_concept_id': 'Int64',
        'value_as_concept_description': 'str',
        'value_as_concept_vocab': 'str',
        'obs_event_field_concept_id': 'Int64',
        'obs_event_field_concept_description': 'str',
        'obs_event_field_concept_vocab': 'str',
        'nomop_phase': 'str'
    },
    'procedure_occurrence_data': {
        'procedure_occurrence_id': 'Int64',
        'person_id': 'Int64',
        'procedure_concept_id': 'Int64',
        'procedure_concept_description': 'str',
        'procedure_concept_vocab': 'str',
        'procedure_date': 'datetime64[ns]',
        'procedure_end_date': 'datetime64[ns]',
        'procedure_type_concept_id': 'Int64',
        'procedure_type_concept_description': 'str',
        'modifier_concept_id': 'Int64',
        'modifier_concept_description': 'str',
        'modifier_concept_vocab': 'str'
    },
    'specimen_data': {
        'specimen_id': 'Int64',
        'person_id': 'Int64',
        'specimen_concept_id': 'Int64',
        'specimen_concept_description': 'str',
        'specimen_date': 'datetime64[ns]',
        'specimen_concept_vocab': 'str',
        'specimen_type_concept_id': 'Int64',
        'specimen_type_concept_description': 'str',
    },
    'drug_exposure_data': {
        'drug_exposure_id': 'Int64',
        'person_id': 'Int64',
        'drug_concept_id': 'Int64',
        'drug_concept_description': 'str',
        'drug_concept_vocab': 'str',
        'drug_exposure_start_date': 'datetime64[ns]',
        'drug_exposure_end_date': 'datetime64[ns]',
        'drug_type_concept_id': 'Int64',
        'drug_type_concept_description': 'str'
    },
    'death_data': {
        'person_id': 'Int64',
        'death_date': 'datetime64[ns]'
    }
}
